# Michał Galant

# Stage 1 : budowanie
FROM node:14-alpine as build

WORKDIR /server

COPY package.json ./
COPY src ./src
COPY public ./public

RUN npm install
RUN npm run build

# Stage 2 : wystawienie
FROM nginx:1.21.1-alpine

COPY --from=build /server/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]